name: emp_gateway
description: Server app for sync employess from MySQL to SQLLite.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.4.0
  dio: ^5.8.0+1
  mysql_client: ^0.0.27
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  sqlite3: ^2.7.5
  yaml: ^3.1.2 
  shelf_cors_headers: ^0.1.5
  path: ^1.9.1
  

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
